import type { UWSubmission, UWRenewal } from './uwTypes'

export const SUBMISSIONS: UWSubmission[] = [
  {
    id: 'fabrikam-manufacturing',
    client: 'Fabrikam Manufacturing',
    broker: 'Adatum',
    brokerContact: 'James Whitfield',
    line: 'Commercial Property',
    tiv: '$2.1B',
    requestedLimit: '$50M',
    submittedAt: 'Overnight · 11:42 PM',
    deadline: 'Today 5:00 PM',
    status: 'urgent',
    flagReasons: [
      'Exceeds authority limit ($50M > $25M primary line)',
      'Protection documentation incomplete',
      'Third-party hazard signal elevated at primary site',
    ],
    aiRecommendation: 'Prioritize — senior referral required. Broker deadline 5:00 PM today.',
    fraudRisk: 'low',
    complianceFlags: ['Authority referral required ($50M exceeds $25M primary line)'],
  },
  {
    id: 'northwind-logistics',
    client: 'Northwind Logistics',
    broker: 'Contoso Brokers',
    brokerContact: 'Priya Anand',
    line: 'General Liability',
    tiv: '$180M',
    requestedLimit: '$5M',
    submittedAt: '2 days ago',
    status: 'pending',
    flagReasons: [
      'Identity verification pending',
      'Prior loss run mismatch — 2021 claim undisclosed',
    ],
    aiRecommendation: 'Request additional documentation from broker before proceeding.',
    fraudRisk: 'moderate',
    complianceFlags: ['Identity verification incomplete', 'Possible material misrepresentation'],
  },
  {
    id: 'alpine-ventures',
    client: 'Alpine Ventures Group',
    broker: 'Proseware Insurance',
    brokerContact: 'Derek Olson',
    line: 'Commercial Property',
    tiv: '$95M',
    requestedLimit: '$12M',
    submittedAt: '1 day ago',
    status: 'pending',
    flagReasons: [
      'ACORD 125 incomplete — sections 4 and 7 missing',
      'Property schedule not attached',
    ],
    aiRecommendation: 'Refer back to broker for missing documents.',
    fraudRisk: 'low',
    complianceFlags: ['Incomplete application'],
  },
  {
    id: 'metro-warehouse',
    client: 'Metro Warehouse Complex',
    broker: 'Woodgrove Premier Brokers',
    brokerContact: 'Sandra Kim',
    line: 'Commercial Property + Equipment Breakdown',
    tiv: '$340M',
    requestedLimit: '$20M',
    submittedAt: '3 days ago',
    status: 'in-review',
    flagReasons: [
      'Sprinkler inspection report overdue (last: 18 months ago)',
      'Open claim from 2023 — reserve unresolved',
    ],
    aiRecommendation: 'Request current inspection. Flag open claim for loss adjuster review.',
    fraudRisk: 'low',
    complianceFlags: [],
  },
]

export const RENEWALS: UWRenewal[] = [
  {
    id: 'fabrikam',
    client: 'Fabrikam Manufacturing',
    broker: 'Adatum',
    renewalDate: 'Jun 28',
    tiv: '$2.1B',
    currentPremium: '$1.24M',
    aiFlag: 'Review required',
    profitabilityTrend: 'improving',
    recommendation: 'Reprice +3% · Expand equipment breakdown coverage',
    churnRisk: 'moderate',
  },
  {
    id: 'northwind',
    client: 'Northwind Logistics',
    broker: 'Contoso Brokers',
    renewalDate: 'Jul 15',
    tiv: '$180M',
    currentPremium: '$285K',
    aiFlag: null,
    profitabilityTrend: 'stable',
    recommendation: 'Renew as-is',
    churnRisk: 'low',
  },
  {
    id: 'alpine',
    client: 'Alpine Ventures Group',
    broker: 'Proseware Insurance',
    renewalDate: 'Jul 22',
    tiv: '$95M',
    currentPremium: '$140K',
    aiFlag: 'Growth opportunity',
    profitabilityTrend: 'strong',
    recommendation: 'Expand GL coverage · Offer multi-line discount',
    churnRisk: 'low',
  },
  {
    id: 'metro',
    client: 'Metro Warehouse Complex',
    broker: 'Woodgrove Premier Brokers',
    renewalDate: 'Aug 3',
    tiv: '$340M',
    currentPremium: '$512K',
    aiFlag: 'Loss trend concern',
    profitabilityTrend: 'declining',
    recommendation: 'Reprice +8% · Require updated sprinkler inspection',
    churnRisk: 'high',
  },
  {
    id: 'pinnacle',
    client: 'Pinnacle State Campus',
    broker: 'Adatum',
    renewalDate: 'Aug 10',
    tiv: '$680M',
    currentPremium: '$890K',
    aiFlag: null,
    profitabilityTrend: 'stable',
    recommendation: 'Renew as-is · Rate adjustment +1.5%',
    churnRisk: 'low',
  },
]

export const PORTFOLIO_METRICS = {
  morning: {
    label: '8:00 AM',
    submissionsProcessed: 0,
    submissionsTotal: 12,
    cycleTimeDays: 4.2,
    pendingDecisions: 5,
    decisionsToday: 0,
    referralsSent: 0,
    quotesSent: 0,
  },
  midday: {
    label: '12:00 PM',
    submissionsProcessed: 7,
    submissionsTotal: 12,
    cycleTimeDays: 4.1,
    pendingDecisions: 3,
    decisionsToday: 4,
    referralsSent: 1,
    quotesSent: 2,
  },
  eod: {
    label: '5:00 PM',
    submissionsProcessed: 9,
    submissionsTotal: 12,
    cycleTimeDays: 4.0,
    pendingDecisions: 1,
    decisionsToday: 6,
    referralsSent: 2,
    quotesSent: 3,
  },
}

export const TEAM_WORKLOAD = [
  { name: 'Eva (You)', submissions: 8, capacity: 12 },
  { name: 'Sarah M.', submissions: 11, capacity: 12 },
  { name: 'Raj P.', submissions: 5, capacity: 12 },
  { name: 'Tom K.', submissions: 9, capacity: 12 },
  { name: 'Lisa H.', submissions: 10, capacity: 12 },
]
